import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Cambay,
  Inter,
  Plus_Jakarta_Sans,
} from "next/font/google";
import "./globals.css";
import GoogleProvider from "@/components/providers/GoogleProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Fonts used by the FoodSpot design system (home / auth / marketing pages).
const cambay = Cambay({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-cambay",
});
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-jakarta",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${cambay.variable} ${inter.variable} ${jakarta.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <GoogleProvider>
          {children}
        </GoogleProvider>
      </body>
    </html>
  );
}